apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: net6-webapi-template
  title: .net6 webapi service
  description: create a .net6 web api
  tags:
    - recommended
    - dotnet
    - webapi
spec:
  owner: example@example.com
  type: service

  parameters:
    - title: component title info
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of component
        description:
          title: Description
          type: string
          description: desc of component
        owner:
          title: Owner
          type: string
          description: owner of component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              Groups

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repo location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com
  steps:
    - id: template
      name: Fetch skeleton + template
      action: fetch:template
      input: 
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: '{{parameters.component_id}}'
          description: '{{parameters.description}}'
          owner: '{{parameters.component_id}}'
          destination: '{{parameters.repoUrl}}'
    
    - id: publish
      name: Publish
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        description: 'This is {{parameters.component_id}}'
        repoUrl: '{{parameters.repoUrl}}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{steps.publish.output.repoContentsUrl}}'
        catalogInfoPath: '/catalog-info.yml'
  
  output:
    remoteUrl: '{{steps.publish.output.remoteUrl}}'
    entityRef: '{{steps.registe.output.entityRef}}'
